# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name=b'Nombre')),
                ('slug', models.SlugField(blank=True, max_length=180, verbose_name=b'Slug')),
            ],
            options={
                'ordering': ['-name'],
                'verbose_name': 'Proyectos',
            },
        ),
    ]
