# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 22:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20160501_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha/Hora de creaci\xc3\xb3n')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name=b'Fecha/Hora de \xc3\xbaltima actualizaci\xc3\xb3n')),
                ('name', models.CharField(max_length=180, verbose_name=b'Asunto')),
                ('details', models.TextField(blank=True, null=True, verbose_name=b'Detalle')),
                ('status', models.IntegerField(choices=[(0, b'Nuevo'), (1, b'Abierto'), (2, b'Asignado'), (3, b'Re-abierto'), (4, b'En progreso'), (10, b'Resuelto'), (11, 'No se resolver\xe1'), (12, b'Duplicado'), (13, b'No reproducible'), (14, b'No es un error')], default=1, verbose_name=b'Estado')),
                ('priority', models.IntegerField(choices=[(1, b'Alta'), (1, b'Media'), (b'0', b'Baja')], default=b'0', verbose_name=b'Prioridad')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name=b'Asignado a')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_issue_created_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_issue_modified_related', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name=b'Proyecto')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(help_text=b'(optional)', upload_to=b'attachments/')),
                ('filename', models.CharField(max_length=120, verbose_name=b'Nombre del archivo')),
                ('details', models.TextField(blank=True, help_text=b'Opcional', verbose_name=b'Detalle')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_attachments', to='issues.Issue')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
            },
        ),
    ]
