# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de creación')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de última actualización')),
                ('name', models.CharField(max_length=180, verbose_name='Asunto')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('status', models.IntegerField(choices=[(0, 'Nuevo'), (1, 'Abierto'), (2, 'Asignado'), (3, 'Re-abierto'), (4, 'En progreso'), (10, 'Resuelto'), (11, 'No se resolverá'), (12, 'Duplicado'), (13, 'No reproducible'), (14, 'No es un error')], default=0, verbose_name='Estado')),
                ('priority', models.IntegerField(choices=[(0, 'Baja'), (1, 'Media'), (2, 'Alta')], default=0, verbose_name='Prioridad')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_issue_created_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_issue_modified_related', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
            },
        ),
        migrations.CreateModel(
            name='IssueAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(help_text='(optional)', upload_to='attachments/')),
                ('filename', models.CharField(max_length=120, verbose_name='Nombre del archivo')),
                ('details', models.TextField(blank=True, help_text='Opcional', verbose_name='Detalle')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_attachments', to='issues.Issue')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'abstract': False,
            },
        ),
    ]
